### ISSUE TITLE
Revise summary

### ISSUE THREAD

**Issue by zacky1972** [zackylab/thesis_yousaikei#7]
> 本研究では，Elixir のライブラリ関数であるNodeによるマルチノードのフォールトトレランスとBroadwayによるSupervisorの耐障害性を活用したパイプラインを提案した．

背景と研究目的，提案内容について，改めて記述してください．

> まず，実験１でパイプラインを使用して，画像を読み取り，グレースケール画像に変換した．

実験１で行ったことの概要は，「パイプラインを使用して画像を読み取りグレースケール画像に変換した」ということですか？それとも，実験１で行ったことの概要は，それに加えて「次に，Evision.threshold/3 を使用してグレースケールイメージをしきい値処理して，バイナリイメージを取得した．最後に，Nx.to\_batched/2 を使用してイメージを分割し，Enum.zip/2 を使用して分割イメージと以前に生成されたファイル名をペアにしてから，各画像は対応するファイルとして保存された．」も含めてですか？

> また, 実験２で abort\_soft()関数が異常終了し, 再起動されたから, supervisorのフォールト トレランス 機能を確認した. 同時に, Bencheeでabort\_soft()関数の平均復帰時間は284.79 nsのデータを取得した. 

どのような目的と方法で実験２を行ったのか，どのような結果が得られたのか，概要を記述してください．

> さらに，実験３でSpawnCoElixirを実装なしの Broadwayパイプラインと実装された Broadway パイプラインを比較して, 2 つのパイプラインの最初の段階で第 3 章で記述した abort\_NIF 関数を呼び出した. 

どのような目的と方法で実験３を行ったのか，どのような結果が得られたのか，概要を記述してください．

> 実験3によりElixirのライブラリ関数であるSpawnCoElixirの動作における親と子のノード間のメッセージ通信を介して，クラッシュの原因となる NIF 関数は子ノードで呼び出されて，子のノードがクラッシュした後でも，親ノードが影響を受けない結論が得られた．

実験3から導かれる結論で何を主張したいのかが，理解できません．

**Comment by MIERAI** [comment]
ご指摘ありがとうごぞいます。
